services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-nonoart_postgres_dev}
    labels:
      - 'ru.antogor.nonoart.project=backend'
      - 'ru.antogor.nonoart.environment=dev'
    environment:
      POSTGRES_INITDB_ARGS: '--locale=C.UTF-8 --encoding=UTF8'
      TZ: 'Europe/Moscow'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_HOST_PORT:-5432}:5432'
    volumes:
      - nonoart_postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nonoart_postgres_dev_data:
